run:
  modules-download-mode: readonly
  timeout: 5m
  skip-dirs:
    - .git
    - .github
    - .vscode
    - dist
  build-tags:
    - integration

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    # - paralleltest
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/axiomhq/axiom-go
  nolintlint:
    require-explanation: true
    require-specific: true
  staticcheck:
    checks:
      - all
      - "-SA1019"
