run:
  modules-download-mode: readonly
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    # - paralleltest
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/axiomhq/axiom-go
  nolintlint:
    require-explanation: true
    require-specific: true
  staticcheck:
    checks:
      - all
      - "-SA1019"

issues:
  exclude-dirs:
    - .git
    - .github
    - .vscode
    - dist
  exclude-rules:
    - linters:
        - gosec
      text: "G115: integer overflow conversion"
      path: _test\.go
