// Code generated by "stringer -type=limitType,LimitScope -linecomment -output=limit_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[limitIngest-1]
	_ = x[limitQuery-2]
	_ = x[limitRate-3]
}

const _limitType_name = "ingestqueryrate"

var _limitType_index = [...]uint8{0, 6, 11, 15}

func (i limitType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_limitType_index)-1 {
		return "limitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _limitType_name[_limitType_index[idx]:_limitType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LimitScopeUnknown-0]
	_ = x[LimitScopeUser-1]
	_ = x[LimitScopeOrganization-2]
	_ = x[LimitScopeAnonymous-3]
}

const _LimitScope_name = "unknownuserorganizationanonymous"

var _LimitScope_index = [...]uint8{0, 7, 11, 23, 32}

func (i LimitScope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LimitScope_index)-1 {
		return "LimitScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LimitScope_name[_LimitScope_index[idx]:_LimitScope_index[idx+1]]
}
