// Code generated by "stringer -type=Operator,MonitorType -linecomment -output=monitors_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyOperator-0]
	_ = x[Below-1]
	_ = x[BelowOrEqual-2]
	_ = x[Above-3]
	_ = x[AboveOrEqual-4]
	_ = x[AboveOrBelow-5]
}

const _Operator_name = "BelowBelowOrEqualAboveAboveOrEqualAboveOrBelow"

var _Operator_index = [...]uint8{0, 0, 5, 17, 22, 34, 46}

func (i Operator) String() string {
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonitorTypeThreshold-0]
	_ = x[MonitorTypeMatchEvent-1]
	_ = x[MonitorTypeAnonalyDetection-2]
}

const _MonitorType_name = "ThresholdMatchEventAnomalyDetection"

var _MonitorType_index = [...]uint8{0, 9, 19, 35}

func (i MonitorType) String() string {
	if i >= MonitorType(len(_MonitorType_index)-1) {
		return "MonitorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitorType_name[_MonitorType_index[i]:_MonitorType_index[i+1]]
}
