// Code generated by "stringer -type=Operator -linecomment -output=monitors_operator_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyOperator-0]
	_ = x[Below-1]
	_ = x[BelowOrEqual-2]
	_ = x[Above-3]
	_ = x[AboveOrEqual-4]
}

const _Operator_name = "BelowBelowOrEqualAboveAboveOrEqual"

var _Operator_index = [...]uint8{0, 0, 5, 17, 22, 34}

func (i Operator) String() string {
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
