// Code generated by "stringer -type=Type -linecomment -output=monitors_type_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Threshold-0]
	_ = x[MatchEvent-1]
}

const _Type_name = "ThresholdMatchEvent"

var _Type_index = [...]uint8{0, 9, 19}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
