// Code generated by "stringer -type=Comparison -linecomment -output=monitors_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyComparison-0]
	_ = x[Below-1]
	_ = x[BelowOrEqual-2]
	_ = x[Above-3]
	_ = x[AboveOrEqual-4]
}

const _Comparison_name = "BelowBelowOrEqualAboveAboveOrEqual"

var _Comparison_index = [...]uint8{0, 0, 5, 17, 22, 34}

func (i Comparison) String() string {
	if i >= Comparison(len(_Comparison_index)-1) {
		return "Comparison(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Comparison_name[_Comparison_index[i]:_Comparison_index[i+1]]
}
