// Code generated by "stringer -type=Type -linecomment -output=notifiers_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pagerduty-1]
	_ = x[Slack-2]
	_ = x[Email-3]
	_ = x[Webhook-4]
}

const _Type_name = "pagerdutyslackemailwebhook"

var _Type_index = [...]uint8{0, 9, 14, 19, 26}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
