// Code generated by "stringer -type=Plan -linecomment -output=orgs_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyPlan-0]
	_ = x[Free-1]
	_ = x[Pro-2]
	_ = x[Enterprise-3]
	_ = x[Comped-4]
}

const _Plan_name = "freeproenterprisecomped"

var _Plan_index = [...]uint8{0, 0, 4, 7, 17, 23}

func (i Plan) String() string {
	if i >= Plan(len(_Plan_index)-1) {
		return "Plan(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Plan_name[_Plan_index[i]:_Plan_index[i+1]]
}
