// Code generated by "stringer -type=OwnerKind -linecomment -output=starred_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OwnedByUser-0]
	_ = x[OwnedByTeam-1]
}

const _OwnerKind_name = "userteam"

var _OwnerKind_index = [...]uint8{0, 4, 8}

func (i OwnerKind) String() string {
	if i >= OwnerKind(len(_OwnerKind_index)-1) {
		return "OwnerKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OwnerKind_name[_OwnerKind_index[i]:_OwnerKind_index[i+1]]
}
