// Code generated by "stringer -type=UserRole -linecomment -output=users_string.go"; DO NOT EDIT.

package axiom

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleCustom-0]
	_ = x[RoleNone-1]
	_ = x[RoleReadOnly-2]
	_ = x[RoleUser-3]
	_ = x[RoleAdmin-4]
	_ = x[RoleOwner-5]
}

const _UserRole_name = "customnoneread-onlyuseradminowner"

var _UserRole_index = [...]uint8{0, 6, 10, 19, 23, 28, 33}

func (i UserRole) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserRole_index)-1 {
		return "UserRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[idx]:_UserRole_index[idx+1]]
}
