// Code generated by "stringer -type=Kind -linecomment -output=kind_string.go"; DO NOT EDIT.

package querylegacy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyKind-0]
	_ = x[Analytics-1]
	_ = x[Stream-2]
	_ = x[APL-3]
}

const _Kind_name = "analyticsstreamapl"

var _Kind_index = [...]uint8{0, 0, 9, 15, 18}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
