// Code generated by "stringer -type=SortOrder -linecomment -output=order_string.go"; DO NOT EDIT.

package builder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SortOrderAsc-1]
	_ = x[SortOrderDesc-2]
}

const _SortOrder_name = "ascdesc"

var _SortOrder_index = [...]uint8{0, 3, 7}

func (i SortOrder) String() string {
	i -= 1
	if i >= SortOrder(len(_SortOrder_index)-1) {
		return "SortOrder(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SortOrder_name[_SortOrder_index[i]:_SortOrder_index[i+1]]
}
