// Code generated by "stringer -type=FilterOp -linecomment -output=where_string.go"; DO NOT EDIT.

package builder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opAnd-1]
	_ = x[opOr-2]
	_ = x[FilterOpEqual-3]
	_ = x[FilterOpNotEqual-4]
	_ = x[FilterOpGreaterThan-5]
	_ = x[FilterOpGreaterThanEqual-6]
	_ = x[FilterOpLessThan-7]
	_ = x[FilterOpLessThanEqual-8]
}

const _FilterOp_name = "andor==!=>>=<<="

var _FilterOp_index = [...]uint8{0, 3, 5, 7, 9, 10, 12, 13, 15}

func (i FilterOp) String() string {
	i -= 1
	if i >= FilterOp(len(_FilterOp_index)-1) {
		return "FilterOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FilterOp_name[_FilterOp_index[i]:_FilterOp_index[i+1]]
}
