// Code generated by "stringer -type=AggregationOp -linecomment -output=aggregation_string.go"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpUnknown-0]
	_ = x[OpCount-1]
	_ = x[OpCountIf-2]
	_ = x[OpDistinct-3]
	_ = x[OpDistinctIf-4]
	_ = x[OpSum-5]
	_ = x[OpSumIf-6]
	_ = x[OpAvg-7]
	_ = x[OpAvgIf-8]
	_ = x[OpMin-9]
	_ = x[OpMinIf-10]
	_ = x[OpMax-11]
	_ = x[OpMaxIf-12]
	_ = x[OpTopk-13]
	_ = x[OpTopkIf-14]
	_ = x[OpPercentiles-15]
	_ = x[OpPercentilesIf-16]
	_ = x[OpHistogram-17]
	_ = x[OpHistogramIf-18]
	_ = x[OpStandardDeviation-19]
	_ = x[OpStandardDeviationIf-20]
	_ = x[OpVariance-21]
	_ = x[OpVarianceIf-22]
	_ = x[OpArgMin-23]
	_ = x[OpArgMax-24]
	_ = x[OpRate-25]
	_ = x[OpMakeSet-26]
	_ = x[OpMakeSetIf-27]
	_ = x[OpMakeList-28]
	_ = x[OpMakeListIf-29]
	_ = x[OpComputed-30]
	_ = x[OpSpotlight-31]
}

const _AggregationOp_name = "unknowncountcountifdistinctdistinctifsumsumifavgavgifminminifmaxmaxiftopktopkifpercentilespercentilesifhistogramhistogramifstdevstdevifvariancevarianceifargminargmaxratemakesetmakesetifmakelistmakelistifcomputedspotlight"

var _AggregationOp_index = [...]uint8{0, 7, 12, 19, 27, 37, 40, 45, 48, 53, 56, 61, 64, 69, 73, 79, 90, 103, 112, 123, 128, 135, 143, 153, 159, 165, 169, 176, 185, 193, 203, 211, 220}

func (i AggregationOp) String() string {
	if i >= AggregationOp(len(_AggregationOp_index)-1) {
		return "AggregationOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AggregationOp_name[_AggregationOp_index[i]:_AggregationOp_index[i+1]]
}
