// Code generated by "stringer -type=Format -linecomment -output=format_string.go"; DO NOT EDIT.

package apl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Legacy-0]
}

const _Format_name = "legacy"

var _Format_index = [...]uint8{0, 6}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
