// Code generated by "stringer -type=Method -linecomment -output=pkce_string.go"; DO NOT EDIT.

package pkce

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethodPlain-1]
	_ = x[MethodS256-2]
}

const _Method_name = "plainS256"

var _Method_index = [...]uint8{0, 5, 9}

func (i Method) String() string {
	i -= 1
	if i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
