name: Dependent PRs

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  merge_group:
    types:
      - checks_requested
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'axiomhq'
    steps:
      - uses: z0al/dependent-issues@v1
        if: github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_READ_TOKEN: ${{ secrets.AXIOM_AUTOMATION_TOKEN }}
        with:
          label: dependent
          keywords: depends on, blocked by, needs, requires
      - uses: LouisBrunner/checks-action@v2.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          token: ${{ github.token }}
          name: Dependent Issues
          conclusion: success
          output: |
            {"summary":"Not checking for dependent issues or PRs on Dependabot PRs."}
