name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  gen-diff:
    name: Codegen diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.18
          - 1.19
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make generate
      - run: git diff --exit-code

  lint:
    name: Lint
    needs: gen-diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.18
          - 1.19
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.18
          - 1.19
      max-parallel: 1
      fail-fast: false
    env:
      AXIOM_URL: ${{ secrets.TESTING_CLOUD_DEV_DEPLOYMENT_URL }}
      AXIOM_TOKEN: ${{ secrets.TESTING_CLOUD_DEV_ACCESS_TOKEN }}
      AXIOM_ORG_ID: ${{ secrets.TESTING_CLOUD_DEV_ORG_ID }}
      AXIOM_DATASET_SUFFIX: ${{ github.run_id }}-${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Test (Unit)
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: make test
      - name: Test (Integration)
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: make test-integration
      - name: Cleanup (On Test Failure)
        if: failure() && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          curl -sL $(curl -s https://api.github.com/repos/axiomhq/cli/releases/latest | grep "http.*linux_amd64.tar.gz" | awk '{print $2}' | sed 's|[\"\,]*||g') | tar xzvf - --strip-components=1 --wildcards -C /usr/local/bin "axiom_*_linux_amd64/axiom"
          axiom dataset list -f=json | jq '.[] | select(.id | contains("${{ github.run_id }}-${{ matrix.go }}")).id' | xargs -r -n1 axiom dataset delete -f

  ci-pass:
    name: CI Pass
    needs:
      - gen-diff
      - lint
      - test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.gen-diff.result != 'success' ||
          needs.lint.result != 'success' ||
          needs.test.result != 'success'
        run: exit 1
