name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  gen-diff:
    name: Codegen diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.17
          - 1.18
          - ^1.19.0-beta.1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make generate
      - run: git diff --exit-code

  lint:
    name: Lint
    needs: gen-diff
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        go:
          - 1.17
          - 1.18
          - ^1.19.0-beta.1
        include:
          - go: ^1.19.0-beta.1
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        deployment:
          - azure-1-staging
          - cloud-dev
        go:
          - 1.17
          - 1.18
          - ^1.19.0-beta.1
        include:
          - deployment: azure-1-staging
            axiom_url: TESTING_AZURE_1_STAGING_DEPLOYMENT_URL
            axiom_token: TESTING_AZURE_1_STAGING_ACCESS_TOKEN
            experimental: true
          - deployment: cloud-dev
            axiom_url: TESTING_CLOUD_DEV_DEPLOYMENT_URL
            axiom_token: TESTING_CLOUD_DEV_ACCESS_TOKEN
            axiom_org_id: TESTING_CLOUD_DEV_ORG_ID
          - deployment: cloud-dev
            go: 1.17
            update-coverage: true
          - deployment: cloud-dev
            go: ^1.19.0-beta.1
            experimental: true
      max-parallel: 1
    env:
      AXIOM_URL: ${{ secrets[matrix.axiom_url] }}
      AXIOM_TOKEN: ${{ secrets[matrix.axiom_token] }}
      AXIOM_ORG_ID: ${{ secrets[matrix.axiom_org_id] }}
      AXIOM_DATASET_SUFFIX: ${{ github.run_id }}-${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make test-integration
      - name: Cleanup (On Test Failure)
        if: failure()
        run: |
          curl -sL $(curl -s https://api.github.com/repos/axiomhq/cli/releases/latest | grep "http.*linux_amd64.tar.gz" | awk '{print $2}' | sed 's|[\"\,]*||g') | tar xzvf - --strip-components=1 --wildcards -C /usr/local/bin "axiom_*_linux_amd64/axiom"
          axiom dataset list -f=json | jq '.[] | select(.id | contains("${{ github.run_id }}-${{ matrix.go }}")).id' | xargs -n1 axiom dataset delete -f
      - name: Update Coverage
        if: matrix.update-coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  ci-pass:
    needs: test
    name: CI Pass
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: CI Pass
          conclusion: ${{ job.status }}
