name: Push

on:
  push:
    branches:
      - main

jobs:
  gen-diff:
    name: Codegen diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: make generate
      - run: git diff --exit-code

  lint:
    name: Lint
    needs: gen-diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
        include:
          - go: 1.17
            update-coverage: true
            update-goreportcard: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - env:
          AXIOM_TOKEN: ${{ secrets.TESTING_AZURE_1_STAGING_ACCESS_TOKEN }}
          AXIOM_URL: ${{ secrets.TESTING_AZURE_1_STAGING_DEPLOYMENT_URL }}
          AXIOM_DATASET_SUFFIX: ${{ github.run_id }}-${{ matrix.go }}
        run: make test-integration
      - name: Update Coverage
        if: ${{ matrix.update-coverage }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
      - name: Update Go Report Card
        if: ${{ matrix.update-goreportcard }}
        uses: creekorful/goreportcard-action@v1.0
