name: Push

on:
  push:
    branches:
      - main

# HINT(lukasmalkmus): Make sure the workflow is only ever run once for each
# commit that has been pushed.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen-diff:
    name: Codegen diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.19"
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: make generate
      - run: git diff --exit-code

  lint:
    name: Lint
    needs: gen-diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.19"
          - "1.20"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: echo "GOLANGCI_LINT_VERSION=$(go list -m -f '{{.Version}}' github.com/golangci/golangci-lint)" >> $GITHUB_ENV
      - uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          # HINT(lukasmalkmus): If we can get rid of the tar errors coming from
          # unpacking the cache zip, we can enable the cache again.
          skip-pkg-cache: true

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    # HINT(lukasmalkmus): Make sure the job is only ever run once per
    # environment, across all active jobs and workflows. Errors on the
    # development environment will not cancel the matrix jobs on the staging
    # environment (and thus not affect the overall workflow status).
    concurrency:
      group: ${{ matrix.environment }}
    continue-on-error: ${{ matrix.environment == 'development' }}
    strategy:
      fail-fast: true
      matrix:
        go:
          - "1.19"
          - "1.20"
        environment:
          - development
          - staging
        include:
          - environment: development
            url: TESTING_DEV_API_URL
            token: TESTING_DEV_TOKEN
            org_id: TESTING_DEV_ORG_ID
          - environment: staging
            url: TESTING_STAGING_API_URL
            token: TESTING_STAGING_TOKEN
            org_id: TESTING_STAGING_ORG_ID
    env:
      AXIOM_URL: ${{ secrets[matrix.url] }}
      AXIOM_TOKEN: ${{ secrets[matrix.token] }}
      AXIOM_ORG_ID: ${{ secrets[matrix.org_id] }}
      AXIOM_DATASET_SUFFIX: ${{ github.run_id }}-${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: make test-integration
      - name: Cleanup (On Test Failure)
        if: failure()
        run: |
          curl -sL $(curl -s https://api.github.com/repos/axiomhq/cli/releases/tags/v0.9.1 | grep "http.*linux_amd64.tar.gz" | awk '{print $2}' | sed 's|[\"\,]*||g') | tar xzvf - --strip-components=1 --wildcards -C /usr/local/bin "axiom_*_linux_amd64/axiom"
          axiom dataset list -f=json | jq '.[] | select(.id | contains("${{ github.run_id }}-${{ matrix.go }}")).id' | xargs -r -n1 axiom dataset delete -f
