name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

# HINT(lukasmalkmus): Make sure release jobs are only ever run once at a time
# (and are never cancelled when new jobs for the same group are queued).
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - run: echo "GORELEASER_VERSION=$(go list -m -f '{{.Version}}' github.com/goreleaser/goreleaser)" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
