name: Server Regression

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# HINT(lukasmalkmus): Make sure the workflow is only ever run once at a time.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Don't run on forks.
    if: github.repository_owner == 'axiomhq'
    # HINT(lukasmalkmus): Make sure the job is only ever run once per
    # environment, across all active jobs and workflows.
    concurrency:
      group: ${{ matrix.environment }}
      cancel-in-progress: false
    strategy:
      matrix:
        go:
          - "1.27"
          - "1.28"
        environment:
          - development
          - staging
        include:
          - environment: development
            slug: DEV
          - environment: staging
            slug: STAGING
    env:
      AXIOM_URL: ${{ secrets[format('TESTING_{0}_API_URL', matrix.slug)] }}
      AXIOM_TOKEN: ${{ secrets[format('TESTING_{0}_TOKEN', matrix.slug)] }}
      AXIOM_ORG_ID: ${{ secrets[format('TESTING_{0}_ORG_ID', matrix.slug)] }}
      AXIOM_EDGE_URL: ${{ vars[format('TESTING_{0}_EDGE_URL', matrix.slug)] }}
      AXIOM_EDGE_TOKEN: ${{ secrets[format('TESTING_{0}_EDGE_TOKEN', matrix.slug)] }}
      AXIOM_EDGE_DEPLOYMENT: ${{ vars[format('TESTING_{0}_EDGE_DATASET_REGION', matrix.slug)] }}
      AXIOM_DATASET_SUFFIX: ${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.go }}
      TELEMETRY_TRACES_URL: ${{ secrets.TELEMETRY_TRACES_URL }}
      TELEMETRY_TRACES_TOKEN: ${{ secrets.TELEMETRY_TRACES_TOKEN }}
      TELEMETRY_TRACES_DATASET: ${{ vars[format('TELEMETRY_{0}_TRACES_DATASET', matrix.slug)] }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - run: make test-integration
      - if: failure() || cancelled()
        uses: axiomhq/cli/actions/setup@v0.19.0
      - name: Cleanup
        if: failure() || cancelled()
        run: |
          axiom dataset list -f=json | jq '.[] | select(.id | contains("${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.go }}")).id' | xargs -r -n1 axiom dataset delete -f
