name: Test Examples

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GOVERSION: "1.17"

jobs:
  run:
    name: Run ${{ matrix.example }} example (${{ matrix.deployment }})
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment:
          - azure-1-staging
          - cloud-dev
        example:
          - apex
          - apl
          - ingestfile
          - logrus
          - query
          - zap
        include:
          - deployment: azure-1-staging
            axiom_url: TESTING_AZURE_1_STAGING_DEPLOYMENT_URL
            axiom_token: TESTING_AZURE_1_STAGING_ACCESS_TOKEN
          - deployment: cloud-dev
            axiom_url: TESTING_CLOUD_DEV_DEPLOYMENT_URL
            axiom_token: TESTING_CLOUD_DEV_ACCESS_TOKEN
            axiom_org_id: TESTING_CLOUD_DEV_ORG_ID
          - example: apex
            verify: |
              axiom dataset info $AXIOM_DATASET -f=json | jq -e 'any( .numEvents ; . == 3 )'
          - example: apl
            setup: |
              echo '[{"mood":"hyped","msg":"This is awesome!"}]' >> logs.json
              axiom ingest $AXIOM_DATASET -f=logs.json -f=logs.json -f=logs.json
              sleep 5
          - example: ingestfile
            setup: |
              echo '[{"mood":"hyped","msg":"This is awesome!"}]' >> logs.json
            verify: |
              axiom dataset info $AXIOM_DATASET -f=json | jq -e 'any( .numEvents ; . == 1 )'
          - example: logrus
            verify: |
              axiom dataset info $AXIOM_DATASET -f=json | jq -e 'any( .numEvents ; . == 3 )'
          - example: query
            setup: |
              echo '[{"mood":"hyped","msg":"This is awesome!"}]' >> logs.json
              axiom ingest $AXIOM_DATASET -f=logs.json -f=logs.json -f=logs.json
              sleep 5
          - example: zap
            verify: |
              axiom dataset info $AXIOM_DATASET -f=json | jq -e 'any( .numEvents ; . == 3 )'
      max-parallel: 1
      fail-fast: false
    env:
      AXIOM_URL: ${{ secrets[matrix.axiom_url] }}
      AXIOM_TOKEN: ${{ secrets[matrix.axiom_token] }}
      AXIOM_ORG_ID: ${{ secrets[matrix.axiom_org_id] }}
      AXIOM_DATASET: test-axiom-go-examples-${{ github.run_id }}-${{ matrix.example }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Setup
        run: |
          go install github.com/axiomhq/cli/cmd/axiom@latest
          axiom dataset create -n=$AXIOM_DATASET -d="Axiom Go examples test"
      - name: Setup ${{ matrix.example }} example
        if: matrix.setup
        run: ${{ matrix.setup}}
      - name: Run ${{ matrix.example }} example
        run: go run ./examples/${{ matrix.example }}/main.go
      - name: Verify ${{ matrix.example }} example
        if: matrix.verify
        run: ${{ matrix.verify}}
      - name: Cleanup
        if: always()
        run: axiom dataset delete -f $AXIOM_DATASET
